import type { ToyProduct } from '../types/toy.types'

export const MOCK_TOYS_DATA: ToyProduct[] = [
  // ==========================================
  // --- TCG (Trading Cards): Pokémon ---
  // ==========================================
  {
    id: 'poke-tcg-1',
    name: 'Pokémon TCG: Scarlet & Violet 151 Elite Trainer Box',
    slug: 'pokemon-tcg-scarlet-violet-151-etb',
    description: 'Relive the original Kanto journey with 9 booster packs of Scarlet & Violet 151, an exclusive Snorlax illustration rare promo card, 65 premium card sleeves, 45 Energy cards, and a collector deck box!',
    category: 'tcg',
    tcgSeries: 'pokemon',
    ageGroup: '6-8',
    pokemonType: 'Pokémon TCG ⚡',
    price: 49.99,
    originalPrice: 54.99,
    discountPercent: 10,
    rating: 4.9,
    reviewCount: 380,
    stock: 25,
    brand: 'The Pokémon Company',
    imageUrl: 'https://images.unsplash.com/photo-1628155930542-3c7a64e2c833?w=600&auto=format&fit=crop&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1628155930542-3c7a64e2c833?w=600&auto=format&fit=crop&q=80',
    ],
    tags: ['Best Seller', 'Pokémon TCG', '151', 'Booster Box'],
    isFeatured: true,
    isBestSeller: true,
    features: [
      '9 Pokémon TCG: Scarlet & Violet 151 booster packs (90 cards total)',
      '1 exclusive full-art foil promo card featuring Snorlax',
      '65 specialty card sleeves featuring original Kanto icons',
      '6 damage-counter dice & 1 competition-legal coin-flip die',
    ],
  },
  {
    id: 'poke-tcg-2',
    name: 'Pokémon TCG: Charizard ex Super-Premium Collection Box',
    slug: 'pokemon-tcg-charizard-ex-premium-collection',
    description: 'Ignite your collection with the ultimate Charizard ex box! Includes 3 etched foil promo cards (Charmander, Charmeleon, and Charizard ex), 10 Pokémon TCG booster packs, and an illuminated card display figure stand.',
    category: 'tcg',
    tcgSeries: 'pokemon',
    ageGroup: '9-12',
    pokemonType: 'Pokémon TCG 🔥',
    price: 79.99,
    originalPrice: 89.99,
    discountPercent: 11,
    rating: 5.0,
    reviewCount: 195,
    stock: 15,
    brand: 'The Pokémon Company',
    imageUrl: 'https://images.unsplash.com/photo-1613771404784-3a5686aa2be3?w=600&auto=format&fit=crop&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1613771404784-3a5686aa2be3?w=600&auto=format&fit=crop&q=80',
    ],
    tags: ['Charizard ex', 'Premium TCG', 'Collector Edition'],
    isFeatured: true,
    isBestSeller: true,
    features: [
      '1 etched foil promo card featuring Charizard ex',
      '2 foil promo cards featuring Charmander and Charmeleon',
      '10 Pokémon TCG booster packs across top modern sets',
      '1 Charizard-themed card display protector stand',
    ],
  },
  {
    id: 'poke-tcg-3',
    name: 'Pokémon TCG: Crown Zenith Special Collection Box',
    slug: 'pokemon-tcg-crown-zenith-special-collection',
    description: 'Uncover the legendary Galarian Gallery! Features 5 Crown Zenith booster packs, an oversized foil promo card featuring Lucario VSTAR, and a collector enamel pin.',
    category: 'tcg',
    tcgSeries: 'pokemon',
    ageGroup: '6-8',
    pokemonType: 'Pokémon TCG 🥊',
    price: 39.99,
    originalPrice: 44.99,
    discountPercent: 11,
    rating: 4.8,
    reviewCount: 220,
    stock: 20,
    brand: 'The Pokémon Company',
    imageUrl: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=600&auto=format&fit=crop&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=600&auto=format&fit=crop&q=80',
    ],
    tags: ['Crown Zenith', 'Pokémon TCG', 'Lucario VSTAR'],
    features: [
      '5 Pokémon TCG: Crown Zenith booster packs',
      '1 etched foil promo card featuring Lucario VSTAR',
      '1 etched foil oversize card featuring Lucario VSTAR',
      '1 collector Lucario metal-finish pin badge',
    ],
  },

  // ==========================================
  // --- TCG (Trading Cards): One Piece ---
  // ==========================================
  {
    id: 'op-tcg-1',
    name: 'One Piece Card Game: Awakening of the New Era (OP-05) Booster Box',
    slug: 'one-piece-cg-op05-booster-box',
    description: 'Celebrate the 1st Anniversary of the One Piece Card Game! Packed with 24 booster packs featuring Luffy Gear 5, Eiichiro Oda signed card, and high-rarity Super Parallel Manga cards.',
    category: 'tcg',
    tcgSeries: 'one-piece',
    ageGroup: '12+',
    pokemonType: 'One Piece TCG 🏴‍☠️',
    price: 84.99,
    rating: 5.0,
    reviewCount: 210,
    stock: 12,
    brand: 'Bandai Namco',
    imageUrl: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=600&auto=format&fit=crop&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=600&auto=format&fit=crop&q=80',
    ],
    tags: ['One Piece TCG', 'Booster Box', 'Gear 5', 'Bandai'],
    isNewArrival: true,
    isFeatured: true,
    features: [
      'Full factory-sealed 24-pack booster box (120 cards total)',
      'Features Gear 5 Luffy, Kaido, Enel, and Revolutionary Army leaders',
      'Chance of pulling ultra-rare Oda signed anniversary card',
      'Official Bandai holographic security tape guarantee',
    ],
  },
  {
    id: 'op-tcg-2',
    name: 'One Piece Card Game: 500 Years in the Future (OP-07) Booster Box',
    slug: 'one-piece-cg-op07-booster-box',
    description: 'Explore Egghead Island with Dr. Vegapunk and the Straw Hat crew! Features revolutionary new Yellow and Blue leaders, Boa Hancock Manga Rare, and brand new archetypes.',
    category: 'tcg',
    tcgSeries: 'one-piece',
    ageGroup: '9-12',
    pokemonType: 'One Piece TCG 🏴‍☠️',
    price: 79.99,
    originalPrice: 85.00,
    discountPercent: 6,
    rating: 4.9,
    reviewCount: 145,
    stock: 18,
    brand: 'Bandai Namco',
    imageUrl: 'https://images.unsplash.com/photo-1590736969955-71cc94801759?w=600&auto=format&fit=crop&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1590736969955-71cc94801759?w=600&auto=format&fit=crop&q=80',
    ],
    tags: ['One Piece TCG', 'OP-07', 'Egghead Island'],
    features: [
      '24 factory-sealed packs per booster box',
      'New leaders including Monkey D. Dragon and Bonney',
      'High-rarity alternate art character cards',
      'Official Bandai tournament legal cards',
    ],
  },

  // ==========================================
  // --- TCG (Trading Cards): Hololive ---
  // ==========================================
  {
    id: 'holo-tcg-1',
    name: 'Hololive Official Card Game: Blooming Radiance Booster Box (hBP01)',
    slug: 'hololive-ocg-blooming-radiance-booster-box',
    description: 'The sensational new official Hololive Card Game by Cover Corp! Features 12 booster packs starring Tokino Sora, Shirakami Fubuki, Usada Pekora, and Hoshimachi Suisei with hot-stamped foil signatures.',
    category: 'tcg',
    tcgSeries: 'hololive',
    ageGroup: '12+',
    pokemonType: 'Hololive TCG 🎤',
    price: 69.99,
    rating: 5.0,
    reviewCount: 165,
    stock: 14,
    brand: 'Cover Corp',
    imageUrl: 'https://images.unsplash.com/photo-1563089145-599997674d42?w=600&auto=format&fit=crop&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1563089145-599997674d42?w=600&auto=format&fit=crop&q=80',
    ],
    tags: ['Hololive TCG', 'Cover Corp', 'Suisei', 'Pekora'],
    isNewArrival: true,
    isFeatured: true,
    features: [
      'Factory-sealed 12-pack booster box (8 cards per pack)',
      'Starring Generation 0, Gen 1, Gen 3, and HoloMyth talents',
      'Chance of pulling exclusive SEC and UR Gold foil signatures',
      'Authentic Cover Corp licensed official card game release',
    ],
  },
  {
    id: 'holo-tcg-2',
    name: 'Weiß Schwarz: Hololive Production Vol.2 Premium Booster Box',
    slug: 'weiss-schwarz-hololive-vol2-booster-box',
    description: 'The monumental Weiß Schwarz Hololive Vol.2 collection by Bushiroad! Features all 53 Hololive Production talents including English and Indonesia branches with dazzling SP foil signatures.',
    category: 'tcg',
    tcgSeries: 'hololive',
    ageGroup: '12+',
    pokemonType: 'Hololive TCG 🎤',
    price: 74.99,
    originalPrice: 82.00,
    discountPercent: 9,
    rating: 4.9,
    reviewCount: 130,
    stock: 10,
    brand: 'Bushiroad',
    imageUrl: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=600&auto=format&fit=crop&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=600&auto=format&fit=crop&q=80',
    ],
    tags: ['Hololive', 'Weiß Schwarz', 'Bushiroad', 'SP Signed'],
    features: [
      '16 booster packs per box with 9 cards each',
      '53 Hololive talents represented across generations',
      'High-rarity hot-stamped voice actress / VTuber signatures',
      'Bushiroad tournament legal deck-building set',
    ],
  },

  // ==========================================
  // --- TCG (Trading Cards): Duel Masters ---
  // ==========================================
  {
    id: 'dm-tcg-1',
    name: 'Duel Masters: DM23-RP4 Abyssal Revolution Final Booster Box',
    slug: 'duel-masters-abyssal-revolution-booster-box',
    description: 'The epic climax of the Abyssal Revolution saga! Packed with 30 packs containing legendary Over Rare and 20th Gold foil cards. Created by Takara Tomy and Wizards of the Coast.',
    category: 'tcg',
    tcgSeries: 'duel-masters',
    ageGroup: '9-12',
    pokemonType: 'Duel Masters ⚔️',
    price: 59.99,
    originalPrice: 65.00,
    discountPercent: 8,
    rating: 4.8,
    reviewCount: 92,
    stock: 16,
    brand: 'Takara Tomy',
    imageUrl: 'https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?w=600&auto=format&fit=crop&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?w=600&auto=format&fit=crop&q=80',
    ],
    tags: ['Duel Masters', 'Takara Tomy', 'Booster Box', 'Japanese TCG'],
    features: [
      '30 booster packs per box (5 cards per pack, 150 total)',
      'Features Over Rare, Super Rare, and Very Rare foil cards',
      'Official Takara Tomy Japanese release with holographic seal',
      'Compatible with standard Japanese Duel Masters formats',
    ],
  },
  {
    id: 'dm-tcg-2',
    name: 'Duel Masters: Legend Super Deck Dragon Overlord Deck Set',
    slug: 'duel-masters-legend-super-deck-dragon',
    description: 'Unleash the supreme might of five-civilization Dragons! Complete tournament-ready 40-card foil deck with specialized protective sleeves and deck case.',
    category: 'tcg',
    tcgSeries: 'duel-masters',
    ageGroup: '9-12',
    pokemonType: 'Duel Masters ⚔️',
    price: 44.99,
    rating: 4.9,
    reviewCount: 88,
    stock: 12,
    brand: 'Takara Tomy',
    imageUrl: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=600&auto=format&fit=crop&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=600&auto=format&fit=crop&q=80',
    ],
    tags: ['Duel Masters', 'Super Deck', 'Dragon Overlord'],
    features: [
      'Full 40-card all-foil competitive ready deck',
      'Includes 42 premium themed card sleeves',
      'Includes hard-shell luxury collector deck case',
      'Features Bolshack and Dragon World boss monsters',
    ],
  },

  // ==========================================
  // --- TCG (Trading Cards): Weiß Schwarz ---
  // ==========================================
  {
    id: 'ws-tcg-1',
    name: 'Weiß Schwarz: Frieren - Beyond Journey\'s End Booster Box',
    slug: 'weiss-schwarz-frieren-booster-box',
    description: 'Relive the magical journey of the elven mage Frieren! Features 16 packs packed with breathtaking anime moments, Fern, Stark, Himmel, and foil stamped cast signatures (SP cards).',
    category: 'tcg',
    tcgSeries: 'weiss-schwarz',
    ageGroup: '12+',
    pokemonType: 'Weiß Schwarz ✨',
    price: 68.99,
    rating: 5.0,
    reviewCount: 155,
    stock: 15,
    brand: 'Bushiroad',
    imageUrl: 'https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=600&auto=format&fit=crop&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=600&auto=format&fit=crop&q=80',
    ],
    tags: ['Weiß Schwarz', 'Frieren', 'Bushiroad', 'Anime TCG'],
    isNewArrival: true,
    isFeatured: true,
    features: [
      '16 booster packs per box (9 cards per pack)',
      'Chance of rare SP stamped signature cards from main voice cast',
      'Exclusive Box Topper PR card included inside',
      'Official Bushiroad tournament legal English/Japanese edition',
    ],
  },
  {
    id: 'ws-tcg-2',
    name: 'Weiß Schwarz: Bocchi the Rock! Trial Deck+ & Booster Set',
    slug: 'weiss-schwarz-bocchi-the-rock-booster-set',
    description: 'Rock out with Kessoku Band! Includes a ready-to-play 50-card Trial Deck plus 4 booster packs starring Hitori Gotoh, Nijika, Ryo, and Kita with glitter foil stage cards.',
    category: 'tcg',
    tcgSeries: 'weiss-schwarz',
    ageGroup: '9-12',
    pokemonType: 'Weiß Schwarz ✨',
    price: 42.99,
    originalPrice: 48.00,
    discountPercent: 10,
    rating: 4.9,
    reviewCount: 110,
    stock: 20,
    brand: 'Bushiroad',
    imageUrl: 'https://images.unsplash.com/photo-1594787318286-3d835c1d207f?w=600&auto=format&fit=crop&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1594787318286-3d835c1d207f?w=600&auto=format&fit=crop&q=80',
    ],
    tags: ['Weiß Schwarz', 'Bocchi the Rock', 'Kessoku Band'],
    features: [
      'Pre-constructed 50-card deck + 4 booster packs',
      '2 shiny RRR or SP foil cards guaranteed in every trial deck',
      'Playmat and quick-start rule sheet included',
      'Perfect entry point for anime card game collectors',
    ],
  },

  // ==========================================
  // --- Anime Figures ---
  // ==========================================
  {
    id: 'poke-fig-1',
    name: 'Mega Pokémon Charizard Fire-Breathing Motion Battle Statue',
    slug: 'mega-charizard-motion-battle-statue',
    description: 'Construct the iconic flame Pokémon Charizard with over 420 pieces! Turn the mechanical crank on the volcanic pedestal to activate authentic wing-flapping and flaming breath motion.',
    category: 'anime-figures',
    ageGroup: '9-12',
    pokemonType: 'Pokémon Figure 🔥',
    price: 54.95,
    originalPrice: 65.00,
    discountPercent: 15,
    rating: 4.9,
    reviewCount: 185,
    stock: 18,
    brand: 'Mega Construx',
    imageUrl: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=600&auto=format&fit=crop&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=600&auto=format&fit=crop&q=80',
    ],
    tags: ['Charizard', 'Fire Type', 'Anime Figure'],
    isFeatured: true,
    isBestSeller: true,
    features: [
      '424 interlocking high-detail sculpted pieces',
      'Mechanical crank triggers authentic wing-flapping action',
      'Poseable flaming tail, articulated jaw, and fierce battle claws',
      'Display stand with rocky terrain and molten lava details',
    ],
    safetyWarning: 'Choking hazard - small parts. Not for children under 3 years.',
  },
  {
    id: 'poke-fig-2',
    name: 'Mewtwo Deluxe Legendary Psychic Blast Action Figure',
    slug: 'mewtwo-legendary-deluxe-battle-figure',
    description: 'Unleash the terrifying psychic might of Genetic Pokémon Mewtwo! Standing 6.5 inches tall with 14 points of articulation and a translucent purple Shadow Ball projectile blast.',
    category: 'anime-figures',
    ageGroup: '6-8',
    pokemonType: 'Pokémon Figure 🔮',
    price: 29.99,
    originalPrice: 34.99,
    discountPercent: 14,
    rating: 4.8,
    reviewCount: 165,
    stock: 22,
    brand: 'Jazwares',
    imageUrl: 'https://images.unsplash.com/photo-1563089145-599997674d42?w=600&auto=format&fit=crop&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1563089145-599997674d42?w=600&auto=format&fit=crop&q=80',
    ],
    tags: ['Mewtwo', 'Psychic Type', 'Legendary Figure'],
    features: [
      'Spring-loaded arm fires launchable Shadow Ball accessory',
      '14 points of dynamic articulation including tail and neck',
      'Translucent psychic energy stand for levitating poses',
      'High-detail anime sculpt capturing Mewtwo\'s cinematic aura',
    ],
  },
  {
    id: 'poke-fig-3',
    name: 'Battle Action 6-Figure Multipack: Kanto Champions',
    slug: 'battle-action-6-figure-multipack',
    description: 'Assemble your champion battle team! Features 6 articulated anime figures: Pikachu, Charmander, Squirtle, Bulbasaur, Lucario, and Shadow Gengar with battle stances.',
    category: 'anime-figures',
    ageGroup: '3-5',
    pokemonType: 'Pokémon Figure 🌈',
    price: 34.99,
    originalPrice: 39.99,
    discountPercent: 12,
    rating: 4.8,
    reviewCount: 172,
    stock: 28,
    brand: 'Jazwares',
    imageUrl: 'https://images.unsplash.com/photo-1590736969955-71cc94801759?w=600&auto=format&fit=crop&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1590736969955-71cc94801759?w=600&auto=format&fit=crop&q=80',
    ],
    tags: ['6-Pack Figures', 'Kanto Starters', 'Battle Figures'],
    isBestSeller: true,
    features: [
      'Includes 6 fan-favorite anime figures in scale',
      'Articulated limbs on larger figures for iconic battle poses',
      'True-to-scale modeling based on official anime heights',
      'Durable collector-grade non-toxic PVC finish',
    ],
  },
  {
    id: 'poke-fig-4',
    name: 'Monkey D. Luffy Gear 5 Sun God Nika Battle Figure',
    slug: 'monkey-d-luffy-gear-5-battle-figure',
    description: 'Unleash the drums of liberation! Spectacular 8-inch dynamic battle figure featuring Luffy in full Gear 5 form with swirling clouds of steam, laughing expression, and pearlescent white hair sculpt.',
    category: 'anime-figures',
    ageGroup: '12+',
    pokemonType: 'One Piece Figure ⚡',
    price: 48.00,
    originalPrice: 55.00,
    discountPercent: 13,
    rating: 5.0,
    reviewCount: 245,
    stock: 14,
    brand: 'Bandai Spirits',
    imageUrl: 'https://images.unsplash.com/photo-1594787318286-3d835c1d207f?w=600&auto=format&fit=crop&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1594787318286-3d835c1d207f?w=600&auto=format&fit=crop&q=80',
    ],
    tags: ['One Piece', 'Gear 5', 'Anime Figure', 'Collector'],
    isNewArrival: true,
    isFeatured: true,
    features: [
      'Dynamic airborne pose with sculpted purple lightning effect stand',
      'High-grade pearlescent paint on white hair and cloud garments',
      'Official Toei Animation licensing gold sticker of authenticity',
      'Collector display box with foil embossed character artwork',
    ],
  },

  // ==========================================
  // --- Anime Merchandise ---
  // ==========================================
  {
    id: 'poke-merch-1',
    name: 'Pikachu 12" Super Soft Electric Cuddle Plush',
    slug: 'pikachu-super-soft-cuddle-plush',
    description: 'The world\'s most beloved Electric-type Pokémon! Made from ultra-plush velvet fabric with embroidered rosy red cheeks, perky ears, and lightning bolt tail. Officially licensed Pokémon Center edition.',
    category: 'anime-merchandise',
    ageGroup: '3-5',
    pokemonType: 'Plush Merch ⚡',
    price: 29.99,
    originalPrice: 34.99,
    discountPercent: 14,
    rating: 5.0,
    reviewCount: 420,
    stock: 35,
    brand: 'Pokémon Center',
    imageUrl: 'https://images.unsplash.com/photo-1613771404784-3a5686aa2be3?w=600&auto=format&fit=crop&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1613771404784-3a5686aa2be3?w=600&auto=format&fit=crop&q=80',
    ],
    tags: ['Best Seller', 'Pikachu', 'Merchandise', 'Plush'],
    isFeatured: true,
    isBestSeller: true,
    features: [
      'Authentic 12-inch scale cuddle plush',
      'Ultra-soft touch minky fleece fabric',
      'Child-safe embroidered facial features',
      'Official Pokémon Company holographic authenticity tag',
    ],
  },
  {
    id: 'poke-merch-2',
    name: 'Snorlax 24" Giant Snoozing Bean Bag Plush',
    slug: 'snorlax-giant-snoozing-bean-bag-plush',
    description: 'The sleepiest Pokémon in Kanto is ready to snooze in your bedroom! Huge 24-inch bean bag plush with soft belly, floppy arms, and sleepy smile.',
    category: 'anime-merchandise',
    ageGroup: '0-2',
    pokemonType: 'Plush Merch 💤',
    price: 69.99,
    originalPrice: 85.00,
    discountPercent: 18,
    rating: 5.0,
    reviewCount: 310,
    stock: 12,
    brand: 'Pokémon Center',
    imageUrl: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=600&auto=format&fit=crop&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=600&auto=format&fit=crop&q=80',
    ],
    tags: ['Giant Plush', 'Snorlax', 'Merchandise'],
    isBestSeller: true,
    features: [
      'Enormous 24-inch bean bag pillow design',
      'High-density memory foam & micro-bead filling',
      'Hypoallergenic, machine-washable removable zippered cover',
      'The ultimate nap companion for anime fans of all ages',
    ],
  },
  {
    id: 'poke-merch-3',
    name: 'Electronic Die-Cast Replica Ultra Ball with Touch Glow',
    slug: 'die-cast-replica-ultra-ball',
    description: 'Officially licensed collector-grade metal Ultra Ball! Engineered with proximity sensors that detect your hand and illuminate the center button with multi-color LED battle glows.',
    category: 'anime-merchandise',
    ageGroup: '12+',
    pokemonType: 'Trainer Gear 🔴',
    price: 89.99,
    rating: 4.9,
    reviewCount: 115,
    stock: 10,
    brand: 'The Wand Company',
    imageUrl: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=600&auto=format&fit=crop&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=600&auto=format&fit=crop&q=80',
    ],
    tags: ['Ultra Ball', 'Collector Replica', 'Merchandise'],
    isNewArrival: true,
    features: [
      'Heavyweight die-cast metal shell with high-gloss lacquer finish',
      'Proximity sensing button changes color when hand approaches',
      'Includes illuminated matte black presentation display case',
      'Individually numbered holographic collector authentication plate',
    ],
  },
  {
    id: 'poke-merch-4',
    name: 'Trainer Clip \'N\' Go Pokéball & Belt Set',
    slug: 'trainer-clip-n-go-pokeball-belt-set',
    description: 'Become an authentic Pokémon trainer! Adjustable waist belt holds up to 6 Pokéballs. Includes 1 Pokéball, 1 Repeat Ball, and a 2-inch battle Pikachu figure.',
    category: 'anime-merchandise',
    ageGroup: '3-5',
    pokemonType: 'Trainer Gear 🔴',
    price: 27.50,
    originalPrice: 32.00,
    discountPercent: 14,
    rating: 4.8,
    reviewCount: 195,
    stock: 30,
    brand: 'Jazwares',
    imageUrl: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=600&auto=format&fit=crop&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=600&auto=format&fit=crop&q=80',
    ],
    tags: ['Trainer Belt', 'Clip N Go', 'Merchandise'],
    features: [
      'Adjustable belt fits kids waist sizes 20 to 32 inches',
      'Pop-open spring latch Pokéballs store standard 2" figures',
      'Compatible with all official Clip \'N\' Go accessories',
      'Includes 1 Pokéball, 1 Repeat Ball, and Pikachu figure',
    ],
  },
  {
    id: 'poke-merch-5',
    name: 'Eevee Evolutions 8-Pin Collector Enamel Badge Set',
    slug: 'eevee-evolutions-collector-badge-set',
    description: 'Stunning luxury enamel pin collection featuring all 8 Eeveelutions: Vaporeon, Jolteon, Flareon, Espeon, Umbreon, Leafeon, Glaceon, and Sylveon with gold-plated metal borders.',
    category: 'anime-merchandise',
    ageGroup: '9-12',
    pokemonType: 'Anime Pins 🦊',
    price: 42.00,
    rating: 5.0,
    reviewCount: 98,
    stock: 14,
    brand: 'Pokémon Center',
    imageUrl: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=600&auto=format&fit=crop&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=600&auto=format&fit=crop&q=80',
    ],
    tags: ['Eevee', 'Pins', 'Badges', 'Merchandise'],
    features: [
      '8 full-color hard enamel pins with dual rubber clutch backs',
      'Polished 24k gold-tone metal borders',
      'Presented in a velvet-lined collector keepsake display case',
      'Official Pokémon Center exclusive limited production',
    ],
  },
  {
    id: 'poke-merch-6',
    name: 'Interactive My Partner Eevee with Sound & Motion',
    slug: 'interactive-my-partner-eevee',
    description: 'Bond with your very own Eevee! Features 50+ playful sound reactions, microphone voice response, head and tail wagging motion, and glowing blush cheeks.',
    category: 'anime-merchandise',
    ageGroup: '3-5',
    pokemonType: 'Interactive Merch ✨',
    price: 38.50,
    rating: 4.9,
    reviewCount: 215,
    stock: 22,
    brand: 'Jazwares',
    imageUrl: 'https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=600&auto=format&fit=crop&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=600&auto=format&fit=crop&q=80',
    ],
    tags: ['Interactive', 'Eevee', 'Sound & Lights', 'Merchandise'],
    isFeatured: true,
    features: [
      'Over 50 unique sound and motion combinations',
      'Touch sensors on head, belly, and back trigger cute reactions',
      'Plays iconic Pokémon anime theme melodies',
      'Includes 3 AAA batteries installed ready to play',
    ],
  },
]
