<?php

namespace Database\Seeders;

use App\Models\RefOnePieceSet;
use App\Models\RefSubcategory;
use Illuminate\Database\Seeder;

class RefOnePieceSetSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $onePieceSubcategory = RefSubcategory::where('desc', 'One Piece')->first();
        $subcategoryId = $onePieceSubcategory?->id;

        $sets = [
            // ================= MAIN BOOSTER EXPANSIONS (OP) =================
            [
                'code' => 'OP-01',
                'name' => 'Romance Dawn',
                'product_line' => 'Main Boosters (OP)',
                'set_type' => 'Booster Pack',
                'release_date' => 'December 2022',
                'status' => 'released',
                'description' => 'The foundation of the One Piece Card Game, kicking off the series with iconic East Blue and Land of Wano characters.',
                'notes' => 'Arc / Thematic Focus: East Blue / Series Launch',
                'chase_cards' => [
                    [
                        'name' => 'Shanks (Manga Alternate Art)',
                        'card_number' => 'OP01-120',
                        'rarity' => 'SEC-Parallel (Manga Rare)',
                        'estimated_value' => '$800 - $1,400+',
                        'description' => 'The premier grail of modern One Piece TCG, featuring original manga panels of Shanks saving Luffy.',
                    ],
                    [
                        'name' => 'Roronoa Zoro (Leader Alt Art)',
                        'card_number' => 'OP01-025',
                        'rarity' => 'L-Parallel',
                        'estimated_value' => '$150 - $280',
                        'description' => 'Dominant Red/Green meta leader with stylized face close-up.',
                    ],
                    [
                        'name' => 'Nami (Alternate Art)',
                        'card_number' => 'OP01-016',
                        'rarity' => 'R-Parallel',
                        'estimated_value' => '$180 - $320',
                        'description' => 'Iconic East Blue Straw Hat searcher in massive collector demand.',
                    ],
                    [
                        'name' => 'Yamato (Secret Rare Parallel)',
                        'card_number' => 'OP01-121',
                        'rarity' => 'SEC-Parallel',
                        'estimated_value' => '$80 - $160',
                        'description' => 'Stunning gold & foil treatment of the Daughter of Kaido.',
                    ],
                ],
                'is_subset' => false,
                'release_order' => 1,
            ],
            [
                'code' => 'OP-02',
                'name' => 'Paramount War',
                'product_line' => 'Main Boosters (OP)',
                'set_type' => 'Booster Pack',
                'release_date' => 'March 2023',
                'status' => 'released',
                'description' => 'Focusing on the tragic and legendary Marineford war, introducing Whitebeard Pirates, Navy Admirals, and Impel Down escapees.',
                'notes' => 'Arc / Thematic Focus: Marineford',
                'chase_cards' => [
                    [
                        'name' => 'Portgas.D.Ace (Manga Alternate Art)',
                        'card_number' => 'OP02-013',
                        'rarity' => 'SR-Parallel (Manga Rare)',
                        'estimated_value' => '$700 - $1,200+',
                        'description' => 'Manga background illustration of Fire Fist Ace from the climax of Marineford.',
                    ],
                    [
                        'name' => 'Edward.Newgate (Leader Alt Art)',
                        'card_number' => 'OP02-001',
                        'rarity' => 'L-Parallel',
                        'estimated_value' => '$120 - $220',
                        'description' => 'The legendary 6-life Whitebeard leader card.',
                    ],
                    [
                        'name' => 'Kuzan (Secret Rare Parallel)',
                        'card_number' => 'OP02-121',
                        'rarity' => 'SEC-Parallel',
                        'estimated_value' => '$70 - $130',
                        'description' => 'Essential Black Navy deck control card featuring Admiral Aokiji.',
                    ],
                    [
                        'name' => 'Uta (Parallel)',
                        'card_number' => 'OP02-120',
                        'rarity' => 'SEC-Parallel',
                        'estimated_value' => '$50 - $95',
                        'description' => 'Film Red heroine commemorative parallel secret rare.',
                    ],
                ],
                'is_subset' => false,
                'release_order' => 2,
            ],
            [
                'code' => 'OP-03',
                'name' => 'Pillars of Strength',
                'product_line' => 'Main Boosters (OP)',
                'set_type' => 'Booster Pack',
                'release_date' => 'June 2023',
                'status' => 'released',
                'description' => 'Introduced Yellow attribute cards, Big Mom Pirates, CP9 assassins, and Fishman Island struggles.',
                'notes' => 'Arc / Thematic Focus: Fishman Island / East Blue',
                'chase_cards' => [
                    [
                        'name' => 'Sogeking (Manga Alternate Art)',
                        'card_number' => 'OP03-122',
                        'rarity' => 'SEC-Parallel (Manga Rare)',
                        'estimated_value' => '$400 - $700+',
                        'description' => 'Usopp as the King of Snipers from Enies Lobby with comic strip background.',
                    ],
                    [
                        'name' => 'Charlotte Katakuri (Alternate Art)',
                        'card_number' => 'OP03-123',
                        'rarity' => 'SEC-Parallel',
                        'estimated_value' => '$75 - $140',
                        'description' => 'The cornerstone 8-cost boss monster for competitive Yellow decks.',
                    ],
                    [
                        'name' => 'Rob Lucci (Leader Alt Art)',
                        'card_number' => 'OP03-076',
                        'rarity' => 'L-Parallel',
                        'estimated_value' => '$60 - $110',
                        'description' => 'CP9 leader parallel card with leopard transformation accents.',
                    ],
                ],
                'is_subset' => false,
                'release_order' => 3,
            ],
            [
                'code' => 'OP-04',
                'name' => 'Kingdoms of Intrigue',
                'product_line' => 'Main Boosters (OP)',
                'set_type' => 'Booster Pack',
                'release_date' => 'September 2023',
                'status' => 'released',
                'description' => 'Relives desert conspiracies of Alabasta and the dramatic Colosseum clashes of Dressrosa.',
                'notes' => 'Arc / Thematic Focus: Alabasta / Dressrosa',
                'chase_cards' => [
                    [
                        'name' => 'Sabo (Manga Alternate Art)',
                        'card_number' => 'OP04-083',
                        'rarity' => 'SR-Parallel (Manga Rare)',
                        'estimated_value' => '$500 - $900+',
                        'description' => 'Manga background rare commemorating the Revolutionary Army Chief of Staff.',
                    ],
                    [
                        'name' => 'Rebecca (Leader Alt Art)',
                        'card_number' => 'OP04-039',
                        'rarity' => 'L-Parallel',
                        'estimated_value' => '$90 - $170',
                        'description' => 'Blue/Black Dressrosa leader with immense artistic and competitive popularity.',
                    ],
                    [
                        'name' => 'Donquixote Doflamingo (Secret Rare Parallel)',
                        'card_number' => 'OP04-119',
                        'rarity' => 'SEC-Parallel',
                        'estimated_value' => '$55 - $110',
                        'description' => 'Heavenly Yaksha parallel foil showcasing the puppet master.',
                    ],
                ],
                'is_subset' => false,
                'release_order' => 4,
            ],
            [
                'code' => 'OP-05',
                'name' => 'Awakening of the New Era',
                'product_line' => 'Main Boosters (OP)',
                'set_type' => 'Booster Pack',
                'release_date' => 'December 2023',
                'status' => 'released',
                'description' => '1st Anniversary booster set celebrating Gear 5 Luffy awakening with unprecedented three manga rares and a signature Oda card.',
                'notes' => 'Arc / Thematic Focus: Skypiea / Revolutionary Army / Gear 5',
                'chase_cards' => [
                    [
                        'name' => 'Monkey.D.Luffy (Gear 5 Manga Rare)',
                        'card_number' => 'OP05-119',
                        'rarity' => 'SEC-Parallel (Manga Rare)',
                        'estimated_value' => '$1,800 - $3,200+',
                        'description' => 'The absolute holy grail of One Piece TCG, showing Gear 5 laughing against the full moon.',
                    ],
                    [
                        'name' => 'Monkey.D.Luffy (Eiichiro Oda Gold Signature)',
                        'card_number' => 'OP05-060',
                        'rarity' => 'Special Parallel (Oda Signed)',
                        'estimated_value' => '$1,200 - $2,000+',
                        'description' => 'Drawn and gold-foil signed by One Piece creator Eiichiro Oda for the 1st Anniversary.',
                    ],
                    [
                        'name' => 'Eustass"Captain"Kid (Manga Alternate Art)',
                        'card_number' => 'OP05-074',
                        'rarity' => 'SR-Parallel (Manga Rare)',
                        'estimated_value' => '$450 - $750',
                        'description' => 'Supernova captain manga art piece from the 1st anniversary trio.',
                    ],
                    [
                        'name' => 'Trafalgar Law (Manga Alternate Art)',
                        'card_number' => 'OP05-069',
                        'rarity' => 'SR-Parallel (Manga Rare)',
                        'estimated_value' => '$550 - $900',
                        'description' => 'Heart Pirates captain manga art piece from the 1st anniversary trio.',
                    ],
                ],
                'is_subset' => false,
                'release_order' => 5,
            ],
            [
                'code' => 'OP-06',
                'name' => 'Wings of the Captain',
                'product_line' => 'Main Boosters (OP)',
                'set_type' => 'Booster Pack',
                'release_date' => 'March 2024',
                'status' => 'released',
                'description' => 'Centered on Zoro and Sanji (Wings of the Pirate King) alongside Thriller Bark and the Vinsmoke Germa 66 squad.',
                'notes' => 'Arc / Thematic Focus: Thriller Bark / Germa 66',
                'chase_cards' => [
                    [
                        'name' => 'Roronoa Zoro (Manga Alternate Art)',
                        'card_number' => 'OP06-118',
                        'rarity' => 'SEC-Parallel (Manga Rare)',
                        'estimated_value' => '$900 - $1,500+',
                        'description' => 'Manga panel background featuring Zoro cutting down King the Conflagration.',
                    ],
                    [
                        'name' => 'Vinsmoke Reiju (Special Parallel / SP)',
                        'card_number' => 'OP06-042',
                        'rarity' => 'SP-Parallel',
                        'estimated_value' => '$130 - $240',
                        'description' => 'Poison Pink premium illustration with high collector affinity.',
                    ],
                    [
                        'name' => 'Gecko Moria (Alternate Art)',
                        'card_number' => 'OP06-086',
                        'rarity' => 'SR-Parallel',
                        'estimated_value' => '$70 - $140',
                        'description' => 'Dominant Black tournament anchor card from Thriller Bark.',
                    ],
                ],
                'is_subset' => false,
                'release_order' => 6,
            ],
            [
                'code' => 'OP-07',
                'name' => '500 Years in the Future',
                'product_line' => 'Main Boosters (OP)',
                'set_type' => 'Booster Pack',
                'release_date' => 'June 2024',
                'status' => 'released',
                'description' => 'Explores the scientific wonder and intrigue of Dr. Vegapunk on Egghead Island and the Worst Generation Supernovas.',
                'notes' => 'Arc / Thematic Focus: Egghead Island / Supernovas',
                'chase_cards' => [
                    [
                        'name' => 'Boa Hancock (Manga Alternate Art)',
                        'card_number' => 'OP07-051',
                        'rarity' => 'SR-Parallel (Manga Rare)',
                        'estimated_value' => '$900 - $1,600+',
                        'description' => 'Pirate Empress Boa Hancock manga panel rare card, one of the most coveted in the game.',
                    ],
                    [
                        'name' => 'Portgas.D.Ace (Leader Alt Art)',
                        'card_number' => 'OP07-001',
                        'rarity' => 'L-Parallel',
                        'estimated_value' => '$80 - $150',
                        'description' => 'Egghead era parallel leader illustration.',
                    ],
                    [
                        'name' => 'Monkey.D.Dragon (Secret Rare Parallel)',
                        'card_number' => 'OP07-119',
                        'rarity' => 'SEC-Parallel',
                        'estimated_value' => '$65 - $120',
                        'description' => 'Supreme Commander of the Revolutionary Army secret rare foil.',
                    ],
                ],
                'is_subset' => false,
                'release_order' => 7,
            ],
            [
                'code' => 'OP-08',
                'name' => 'Two Legends',
                'product_line' => 'Main Boosters (OP)',
                'set_type' => 'Booster Pack',
                'release_date' => 'September 2024',
                'status' => 'released',
                'description' => 'Features Pirate King Gol D. Roger and Dark King Silvers Rayleigh, highlighting Drum Kingdom, Zou, and the Roger Pirates.',
                'notes' => 'Arc / Thematic Focus: Drum Kingdom / Zou / Roger Pirates',
                'chase_cards' => [
                    [
                        'name' => 'Silvers Rayleigh (Manga Alternate Art)',
                        'card_number' => 'OP08-118',
                        'rarity' => 'SEC-Parallel (Manga Rare)',
                        'estimated_value' => '$650 - $1,100+',
                        'description' => 'Dark King Silvers Rayleigh sword swipe with manga background panels.',
                    ],
                    [
                        'name' => 'Gol D. Roger (Secret Rare Parallel)',
                        'card_number' => 'OP08-119',
                        'rarity' => 'SEC-Parallel',
                        'estimated_value' => '$90 - $180',
                        'description' => 'The King of the Pirates in majestic gold and silver foil.',
                    ],
                    [
                        'name' => 'Kalgara & Noland (Leader Alt Arts)',
                        'card_number' => 'OP08-098',
                        'rarity' => 'L-Parallel',
                        'estimated_value' => '$40 - $80',
                        'description' => 'Historical Great Warrior and Explorer parallel leaders.',
                    ],
                ],
                'is_subset' => false,
                'release_order' => 8,
            ],
            [
                'code' => 'OP-09',
                'name' => 'Emperors in the New World',
                'product_line' => 'Main Boosters (OP)',
                'set_type' => 'Booster Pack',
                'release_date' => 'December 2024',
                'status' => 'released',
                'description' => '2nd Anniversary expansion focusing on the Four Emperors (Yonko): Luffy, Shanks, Blackbeard, and Buggy.',
                'notes' => 'Arc / Thematic Focus: The Four Emperors',
                'chase_cards' => [
                    [
                        'name' => 'Marshall.D.Teach (Manga Alternate Art)',
                        'card_number' => 'OP09-093',
                        'rarity' => 'SR-Parallel (Manga Rare)',
                        'estimated_value' => '$800 - $1,400+',
                        'description' => 'Emperor Blackbeard wielding the Dark-Dark and Tremor-Tremor powers.',
                    ],
                    [
                        'name' => 'Shanks (Gold / Silver Anniversary Parallel)',
                        'card_number' => 'OP09-004',
                        'rarity' => 'Super Special Anniversary Parallel',
                        'estimated_value' => '$1,000 - $1,800+',
                        'description' => '2nd Anniversary tribute card celebrating Red-Haired Shanks.',
                    ],
                    [
                        'name' => 'Buggy the Genius Jester (Leader Alt Art)',
                        'card_number' => 'OP09-058',
                        'rarity' => 'L-Parallel',
                        'estimated_value' => '$70 - $130',
                        'description' => 'Cross Guild Emperor parallel leader.',
                    ],
                ],
                'is_subset' => false,
                'release_order' => 9,
            ],
            [
                'code' => 'OP-10',
                'name' => 'Royal Blood',
                'product_line' => 'Main Boosters (OP)',
                'set_type' => 'Booster Pack',
                'release_date' => 'March 2025',
                'status' => 'released',
                'description' => 'Focuses on noble lineage, Dressrosa royalty, World Government bloodlines, and Marines.',
                'notes' => 'Arc / Thematic Focus: Dressrosa / Marines',
                'chase_cards' => [
                    [
                        'name' => 'Trafalgar Law (Manga Alternate Art Vol. 2)',
                        'card_number' => 'OP10-118',
                        'rarity' => 'SEC-Parallel (Manga Rare)',
                        'estimated_value' => '$750 - $1,300+',
                        'description' => 'Surgeon of Death manga sequence foil card.',
                    ],
                    [
                        'name' => 'Issho Fujitora & Ryokugyu (Marines SP)',
                        'card_number' => 'OP10-022',
                        'rarity' => 'SP-Parallel',
                        'estimated_value' => '$90 - $180',
                        'description' => 'New Navy Admirals special collector foil.',
                    ],
                ],
                'is_subset' => false,
                'release_order' => 10,
            ],
            [
                'code' => 'OP-11',
                'name' => 'A Fist of Divine Speed',
                'product_line' => 'Main Boosters (OP)',
                'set_type' => 'Booster Pack',
                'release_date' => 'June 2025',
                'status' => 'released',
                'description' => 'Explosive Whole Cake Island showdowns, Charlotte Family Sweet Commanders, and the Vinsmoke scientific fleet.',
                'notes' => 'Arc / Thematic Focus: Whole Cake Island / Vinsmoke Family',
                'chase_cards' => [
                    [
                        'name' => 'Charlotte Katakuri (Manga Alternate Art)',
                        'card_number' => 'OP11-118',
                        'rarity' => 'SEC-Parallel (Manga Rare)',
                        'estimated_value' => '$800 - $1,400+',
                        'description' => 'Manga panel rare of Katakuri during his mirror world duel with Luffy.',
                    ],
                    [
                        'name' => 'Sanji (Stealth Black / Diable Jambe SP)',
                        'card_number' => 'OP11-065',
                        'rarity' => 'SP-Parallel',
                        'estimated_value' => '$110 - $220',
                        'description' => 'Germa science meets Cook of the Straw Hats special parallel.',
                    ],
                ],
                'is_subset' => false,
                'release_order' => 11,
            ],
            [
                'code' => 'OP-12',
                'name' => 'Legacy of the Master',
                'product_line' => 'Main Boosters (OP)',
                'set_type' => 'Booster Pack',
                'release_date' => 'September 2025',
                'status' => 'released',
                'description' => 'Honoring legendary master and pupil bonds throughout the pirate world (Rayleigh/Luffy, Garp/Koby, Mihawk/Zoro, Zeff/Sanji).',
                'notes' => 'Arc / Thematic Focus: Mentor & Student Pairs',
                'chase_cards' => [
                    [
                        'name' => 'Monkey D. Garp & Koby (Manga Alternate Art)',
                        'card_number' => 'OP12-118',
                        'rarity' => 'SEC-Parallel (Manga Rare)',
                        'estimated_value' => '$850 - $1,500+',
                        'description' => 'Galaxy Impact and Honesty Impact master-student manga sequence.',
                    ],
                    [
                        'name' => 'Silvers Rayleigh & Luffy (Master Parallel)',
                        'card_number' => 'OP12-001',
                        'rarity' => 'L-Parallel',
                        'estimated_value' => '$120 - $250',
                        'description' => 'Haki training on Rusukaina special artwork.',
                    ],
                ],
                'is_subset' => false,
                'release_order' => 12,
            ],
            [
                'code' => 'OP-13',
                'name' => 'Carrying On His Will',
                'product_line' => 'Main Boosters (OP)',
                'set_type' => 'Booster Pack',
                'release_date' => 'December 2025',
                'status' => 'released',
                'description' => 'Centered on the sworn brotherhood of sake cups: Ace, Sabo, and Luffy, and the inherited will of D.',
                'notes' => 'Arc / Thematic Focus: The Three Brothers (Ace, Sabo, Luffy)',
                'chase_cards' => [
                    [
                        'name' => 'Three Brothers (Ace, Sabo, Luffy) Super Parallel Manga',
                        'card_number' => 'OP13-119',
                        'rarity' => 'SEC-Parallel (Manga Rare)',
                        'estimated_value' => '$1,200 - $2,200+',
                        'description' => 'Tricolor manga panel rare depicting childhood oaths and adult destinies.',
                    ],
                    [
                        'name' => 'Flame Emperor Sabo (Leader Alt Art)',
                        'card_number' => 'OP13-002',
                        'rarity' => 'L-Parallel',
                        'estimated_value' => '$100 - $200',
                        'description' => 'High-voltage flame artwork of the Revolutionary hero.',
                    ],
                ],
                'is_subset' => false,
                'release_order' => 13,
            ],
            [
                'code' => 'OP-14',
                'name' => "The Azure Sea's Seven",
                'product_line' => 'Main Boosters (OP)',
                'set_type' => 'Booster Pack',
                'release_date' => 'March 2026',
                'status' => 'released',
                'description' => 'Showcases the Seven Warlords of the Sea (Shichibukai). Note: English release incorporates cards from subset EB-04.',
                'notes' => 'Arc / Thematic Focus: Seven Warlords of the Sea (Merged with EB-04 Egghead cards in English)',
                'chase_cards' => [
                    [
                        'name' => 'Dracule Mihawk (Manga Alternate Art)',
                        'card_number' => 'OP14-118',
                        'rarity' => 'SEC-Parallel (Manga Rare)',
                        'estimated_value' => '$950 - $1,700+',
                        'description' => "World's Greatest Swordsman unleashing black blade Yoru in manga background glory.",
                    ],
                    [
                        'name' => 'Sir Crocodile (Leader Alt Art)',
                        'card_number' => 'OP14-003',
                        'rarity' => 'L-Parallel',
                        'estimated_value' => '$90 - $180',
                        'description' => 'Cross Guild founder sand-blade textured foil.',
                    ],
                ],
                'is_subset' => false,
                'release_order' => 14,
            ],
            [
                'code' => 'OP-15',
                'name' => "Adventure on Kami's Island",
                'product_line' => 'Main Boosters (OP)',
                'set_type' => 'Booster Pack',
                'release_date' => 'June 2026',
                'status' => 'released',
                'description' => 'Return to the white clouds of Skypiea and Upper Yard, with God Enel and Shandian warriors. Also includes merged cards from EB-04 in English.',
                'notes' => 'Arc / Thematic Focus: Skypiea / Enel (Merged with EB-04 Egghead cards in English)',
                'chase_cards' => [
                    [
                        'name' => 'God Enel (Manga Alternate Art)',
                        'card_number' => 'OP15-118',
                        'rarity' => 'SEC-Parallel (Manga Rare)',
                        'estimated_value' => '$850 - $1,500+',
                        'description' => 'Lightning God 200,000,000 Volts Amaru manga panel foil.',
                    ],
                    [
                        'name' => 'Wyper the Berserker (Leader Alt Art)',
                        'card_number' => 'OP15-001',
                        'rarity' => 'L-Parallel',
                        'estimated_value' => '$70 - $130',
                        'description' => 'Shandian champion reject-dial special art.',
                    ],
                ],
                'is_subset' => false,
                'release_order' => 15,
            ],
            [
                'code' => 'OP-16',
                'name' => 'The Time of Battle',
                'product_line' => 'Main Boosters (OP)',
                'set_type' => 'Booster Pack',
                'release_date' => 'September 2026',
                'status' => 'released',
                'description' => 'Revisits the historic Paramount War Part 2 with the supreme Marine Admirals and Blackbeard usurpation.',
                'notes' => 'Arc / Thematic Focus: Paramount War Part 2 / The Admirals',
                'chase_cards' => [
                    [
                        'name' => 'Fleet Admiral Sakazuki / Akainu (Manga Alternate Art)',
                        'card_number' => 'OP16-118',
                        'rarity' => 'SEC-Parallel (Manga Rare)',
                        'estimated_value' => '$900 - $1,600+',
                        'description' => 'Thorough Justice Mag-Mag fruit magma eruption manga panels.',
                    ],
                    [
                        'name' => 'Sengoku the Buddha (Special Parallel)',
                        'card_number' => 'OP16-002',
                        'rarity' => 'SP-Parallel',
                        'estimated_value' => '$85 - $160',
                        'description' => 'Golden shockwave embossed collector foil.',
                    ],
                ],
                'is_subset' => false,
                'release_order' => 16,
            ],
            [
                'code' => 'OP-17',
                'name' => "The World's Strongest Warriors",
                'product_line' => 'Main Boosters (OP)',
                'set_type' => 'Booster Pack',
                'release_date' => 'December 2026',
                'status' => 'upcoming',
                'description' => 'Epic expansion spotlighting the legendary Giants of Elbaf and the mythic Rocks Pirates (Rocks D. Xebec, young Whitebeard, Kaido, Big Mom).',
                'notes' => 'Arc / Thematic Focus: Elbaf / The Rocks Pirates',
                'chase_cards' => [
                    [
                        'name' => 'Rocks D. Xebec (Manga Alternate Art)',
                        'card_number' => 'OP17-118',
                        'rarity' => 'SEC-Parallel (Manga Rare)',
                        'estimated_value' => '$1,500 - $2,500+ (Projected)',
                        'description' => 'The mythic Captain of the Rocks Pirates illustrated in historic manga secrecy.',
                    ],
                    [
                        'name' => 'Dorry & Brogy / Elbaf Giants (Leader Alt Art)',
                        'card_number' => 'OP17-001',
                        'rarity' => 'L-Parallel',
                        'estimated_value' => '$100 - $220 (Projected)',
                        'description' => 'Hakoku Sovereignty dual giant leader art.',
                    ],
                ],
                'is_subset' => false,
                'release_order' => 17,
            ],

            // ================= EXTRA BOOSTERS (EB) =================
            [
                'code' => 'EB-01',
                'name' => 'Memorial Collection',
                'product_line' => 'Extra Boosters (EB)',
                'set_type' => 'Extra Booster',
                'release_date' => 'May 2024',
                'status' => 'released',
                'description' => 'The first extra booster, revisiting classic scenes and strengthening older archetypes.',
                'notes' => 'Arc / Thematic Focus: Memorial Scenes & Niche Archetypes. Extra Boosters are smaller, supplementary sets designed to add support to older deck archetypes.',
                'chase_cards' => [
                    [
                        'name' => 'Tony Tony Chopper (Manga Alternate Art)',
                        'card_number' => 'EB01-006',
                        'rarity' => 'SEC-Parallel (Manga Rare)',
                        'estimated_value' => '$400 - $650+',
                        'description' => 'The undisputed #1 grail of EB-01 featuring manga background panels.',
                    ],
                    [
                        'name' => 'Mr. 2. Bon. Kurei (Bentham)',
                        'card_number' => 'EB01-061',
                        'rarity' => 'SEC-Parallel',
                        'estimated_value' => '$80 - $140',
                        'description' => 'Essential tournament staple for Purple decks with massive competitive playability.',
                    ],
                    [
                        'name' => 'Kouzuki Oden',
                        'card_number' => 'EB01-056',
                        'rarity' => 'SEC-Parallel',
                        'estimated_value' => '$40 - $75',
                        'description' => 'High-demand secret rare parallel celebrating the Wano Country legend.',
                    ],
                    [
                        'name' => 'Cavendish',
                        'card_number' => 'EB01-012',
                        'rarity' => 'SR-Parallel',
                        'estimated_value' => '$45 - $80',
                        'description' => 'Top-tier Supernova archetype searcher and combatant.',
                    ],
                ],
                'is_subset' => true,
                'release_order' => 18,
            ],
            [
                'code' => 'EB-02',
                'name' => 'Anime 25th Collection',
                'product_line' => 'Extra Boosters (EB)',
                'set_type' => 'Extra Booster',
                'release_date' => 'May 2025',
                'status' => 'released',
                'description' => 'A commemorative set celebrating the 25th anniversary of the One Piece anime with classic anime opening and key scene animations.',
                'notes' => 'Arc / Thematic Focus: Anime 25th Anniversary / Iconic TV Scenes',
                'chase_cards' => [
                    [
                        'name' => 'Monkey.D.Luffy (25th Anime Anniversary Special Manga/Animation Rare)',
                        'card_number' => 'EB02-001',
                        'rarity' => 'SEC-Parallel (25th Special Rare)',
                        'estimated_value' => '$600 - $1,100+',
                        'description' => 'Exclusive silver & holographic finish commemorating 25 years of animation.',
                    ],
                    [
                        'name' => 'We Are! Straw Hat Crew (Commemorative Art)',
                        'card_number' => 'EB02-060',
                        'rarity' => 'SP-Parallel',
                        'estimated_value' => '$120 - $220',
                        'description' => 'Original 1999 TV Opening iconic group pose illustration.',
                    ],
                    [
                        'name' => 'Portgas D. Ace & Edward Newgate (Memorial Foil)',
                        'card_number' => 'EB02-030',
                        'rarity' => 'SR-Parallel',
                        'estimated_value' => '$70 - $130',
                        'description' => 'Emotional TV scene parallel treatment.',
                    ],
                ],
                'is_subset' => true,
                'release_order' => 19,
            ],
            [
                'code' => 'EB-03',
                'name' => 'Heroines Edition',
                'product_line' => 'Extra Boosters (EB)',
                'set_type' => 'Extra Booster',
                'release_date' => 'February 2026',
                'status' => 'released',
                'description' => 'A character-focused set spotlighting the prominent women of One Piece, which notably introduced the first Nefeltari Vivi Leader.',
                'notes' => 'Arc / Thematic Focus: Heroines of One Piece / First Nefeltari Vivi Leader',
                'chase_cards' => [
                    [
                        'name' => 'Nami (Heroines Special Manga Art)',
                        'card_number' => 'EB03-005',
                        'rarity' => 'SEC-Parallel (Manga Rare)',
                        'estimated_value' => '$800 - $1,500+',
                        'description' => 'The ultimate chase card of the Heroines subset with manga panel montage.',
                    ],
                    [
                        'name' => 'Nefeltari Vivi (Leader Alt Art)',
                        'card_number' => 'EB03-001',
                        'rarity' => 'L-Parallel',
                        'estimated_value' => '$140 - $260',
                        'description' => 'The groundbreaking first dedicated Nefeltari Vivi Leader card.',
                    ],
                    [
                        'name' => 'Nico Robin (Secret Rare Parallel)',
                        'card_number' => 'EB03-055',
                        'rarity' => 'SEC-Parallel',
                        'estimated_value' => '$90 - $180',
                        'description' => 'Elegant flower-blooming archetypal art piece.',
                    ],
                    [
                        'name' => 'Boa Hancock (Empress Parallel)',
                        'card_number' => 'EB03-020',
                        'rarity' => 'SR-Parallel',
                        'estimated_value' => '$80 - $160',
                        'description' => 'High-gloss textured parallel card.',
                    ],
                ],
                'is_subset' => true,
                'release_order' => 20,
            ],
            [
                'code' => 'EB-04',
                'name' => 'Egghead Crisis',
                'product_line' => 'Extra Boosters (EB)',
                'set_type' => 'Extra Booster',
                'release_date' => 'Mid 2026',
                'status' => 'released',
                'description' => 'Focused on Egghead arc escalations and Vegapunk satellite defense.',
                'notes' => 'Note for English Collectors: While this was a standalone subset in Japan, Bandai opted not to release a standalone EB-04 box in English. Instead, the cards were merged directly into the main English booster boxes for OP-14 (The Azure Sea’s Seven) and OP-15 (Adventure on Kami’s Island).',
                'chase_cards' => [
                    [
                        'name' => 'Jewelry Bonney (Manga Alternate Art - Japanese Exclusive Pack)',
                        'card_number' => 'EB04-010',
                        'rarity' => 'SEC-Parallel (Manga Rare)',
                        'estimated_value' => '$500 - $950+ (Japanese version)',
                        'description' => 'Egghead Future clothes Bonney manga chase card from the standalone Japanese subset.',
                    ],
                    [
                        'name' => 'Dr. Vegapunk (Lilith & Atlas Parallel)',
                        'card_number' => 'EB04-035',
                        'rarity' => 'SR-Parallel',
                        'estimated_value' => '$60 - $120',
                        'description' => 'Satellite cybernetic foil card.',
                    ],
                ],
                'is_subset' => true,
                'release_order' => 21,
            ],
            [
                'code' => 'EB-05',
                'name' => 'Heroines Edition Vol. 2',
                'product_line' => 'Extra Boosters (EB)',
                'set_type' => 'Extra Booster',
                'release_date' => 'October 2026',
                'status' => 'upcoming',
                'description' => 'The second wave of the female-character-focused extra booster line, bringing new leaders and support.',
                'notes' => 'Arc / Thematic Focus: Heroines Volume 2 / Upcoming October 2026 release.',
                'chase_cards' => [
                    [
                        'name' => 'Yamato (Heroines Vol. 2 Manga Alternate Art)',
                        'card_number' => 'EB05-001',
                        'rarity' => 'SEC-Parallel (Manga Rare)',
                        'estimated_value' => '$750 - $1,300+ (Projected)',
                        'description' => 'Anticipated headline grail card with manga panel background.',
                    ],
                    [
                        'name' => 'Uta (New Song World Parallel)',
                        'card_number' => 'EB05-025',
                        'rarity' => 'SEC-Parallel',
                        'estimated_value' => '$110 - $220 (Projected)',
                        'description' => 'Vibrant rainbow foil treatment.',
                    ],
                ],
                'is_subset' => true,
                'release_order' => 22,
            ],

            // ================= PREMIUM BOOSTERS (PRB) =================
            [
                'code' => 'PRB-01',
                'name' => 'Premium Booster - The Best',
                'product_line' => 'Premium Boosters (PRB)',
                'set_type' => 'Premium Booster',
                'release_date' => 'November 2024',
                'status' => 'released',
                'description' => 'A massive 20-pack reprint set that gathered the most popular and competitively viable cards from sets OP-01 through OP-06, alongside event-exclusive promos.',
                'notes' => 'Arc / Thematic Focus: Best of OP-01 through OP-06 Reprints & Event Promos. Premium Boosters are high-end, collector-focused reprint sets that upgrade fan-favorite tournament cards with special foil treatments and new alternate arts.',
                'chase_cards' => [
                    [
                        'name' => 'Monkey.D.Luffy (Donquixote Doflamingo / Kaido / Katakuri Full Face Leader Parallel)',
                        'card_number' => 'PRB01-L01',
                        'rarity' => 'L-Parallel (Premium Foil)',
                        'estimated_value' => '$180 - $350',
                        'description' => 'Gorgeous brand-new full bleed leader reprint treatments.',
                    ],
                    [
                        'name' => 'Nami (New Alternate Art Foil Reprint)',
                        'card_number' => 'OP01-016 (PRB01 Art)',
                        'rarity' => 'R-Parallel (New Art)',
                        'estimated_value' => '$150 - $280',
                        'description' => 'Completely new dynamic art for the essential searcher.',
                    ],
                    [
                        'name' => 'Roronoa Zoro (New Alternate Art Foil Reprint)',
                        'card_number' => 'OP01-025 (PRB01 Art)',
                        'rarity' => 'SR-Parallel (New Art)',
                        'estimated_value' => '$120 - $220',
                        'description' => 'Fresh illustration of the iconic 3-cost Rush attacker.',
                    ],
                    [
                        'name' => 'Charlotte Katakuri (New Alternate Art Foil Reprint)',
                        'card_number' => 'OP03-123 (PRB01 Art)',
                        'rarity' => 'SEC-Parallel (New Art)',
                        'estimated_value' => '$100 - $190',
                        'description' => 'New artwork for the legendary 8-cost Yellow finisher.',
                    ],
                    [
                        'name' => 'Gold DON!! Premium Cards',
                        'card_number' => 'PRB01-DON-GOLD',
                        'rarity' => 'Gold Foil Stamped DON!!',
                        'estimated_value' => '$50 - $120 each',
                        'description' => 'High-end gold foil embossed DON!! energy cards.',
                    ],
                ],
                'is_subset' => true,
                'release_order' => 23,
            ],
            [
                'code' => 'PRB-02',
                'name' => 'The Best Vol. 2',
                'product_line' => 'Premium Boosters (PRB)',
                'set_type' => 'Premium Booster',
                'release_date' => 'October 2025',
                'status' => 'released',
                'description' => 'The second premium wave, bringing more alternate arts and highly sought-after foil treatments for meta-relevant cards from OP-07 through OP-11.',
                'notes' => 'Arc / Thematic Focus: Best of OP-07 through OP-11 Reprints & Championship Foils.',
                'chase_cards' => [
                    [
                        'name' => 'Monkey.D.Luffy (Gear 5 Premium Foil Redux)',
                        'card_number' => 'PRB02-001',
                        'rarity' => 'SEC-Parallel (Premium Redux)',
                        'estimated_value' => '$400 - $800+',
                        'description' => 'Re-imagined foil treatment of the sun god awakening.',
                    ],
                    [
                        'name' => 'Boa Hancock (New Alternate Art Foil)',
                        'card_number' => 'OP07-051 (PRB02 Art)',
                        'rarity' => 'SR-Parallel (New Art)',
                        'estimated_value' => '$200 - $380',
                        'description' => 'Brand new exclusive illustration for the Pirate Empress.',
                    ],
                    [
                        'name' => 'Silvers Rayleigh (New Alternate Art Foil)',
                        'card_number' => 'OP08-118 (PRB02 Art)',
                        'rarity' => 'SEC-Parallel (New Art)',
                        'estimated_value' => '$150 - $290',
                        'description' => 'Dark King high-rarity collector reprint.',
                    ],
                    [
                        'name' => 'Prismatic Gold DON!! Vol. 2',
                        'card_number' => 'PRB02-DON',
                        'rarity' => 'Prismatic Gold DON!!',
                        'estimated_value' => '$120 - $250',
                        'description' => 'Enhanced 3D embossed gold foil energy cards.',
                    ],
                ],
                'is_subset' => true,
                'release_order' => 24,
            ],
        ];

        foreach ($sets as $set) {
            $set['subcategories_id'] = $subcategoryId;
            RefOnePieceSet::updateOrCreate(
                ['code' => $set['code']],
                $set
            );
        }
    }
}
