<?php

namespace Database\Seeders;

use App\Models\RefPokemonSet;
use Illuminate\Database\Seeder;

class RefPokemonSetSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $sets = [
            // Scarlet & Violet Series (2023–2025)
            [
                'series' => 'Scarlet & Violet',
                'series_years' => '2023–2025',
                'japanese_set' => 'Scarlet ex / Violet ex',
                'japanese_code' => 'SV1S / SV1V',
                'english_set' => 'Scarlet & Violet Base Set',
                'set_type' => 'Main Expansion',
                'notes' => null,
                'release_order' => 1,
            ],
            [
                'series' => 'Scarlet & Violet',
                'series_years' => '2023–2025',
                'japanese_set' => 'Triplet Beat',
                'japanese_code' => 'SV1a',
                'english_set' => 'Paldea Evolved',
                'set_type' => 'Subset',
                'notes' => 'Cards combined into English Paldea Evolved',
                'release_order' => 2,
            ],
            [
                'series' => 'Scarlet & Violet',
                'series_years' => '2023–2025',
                'japanese_set' => 'Snow Hazard / Clay Burst',
                'japanese_code' => 'SV2P / SV2D',
                'english_set' => 'Paldea Evolved',
                'set_type' => 'Main Expansion',
                'notes' => 'Cards combined into English Paldea Evolved',
                'release_order' => 3,
            ],
            [
                'series' => 'Scarlet & Violet',
                'series_years' => '2023–2025',
                'japanese_set' => 'Pokémon Card 151',
                'japanese_code' => 'SV2a',
                'english_set' => 'Scarlet & Violet—151',
                'set_type' => 'Subset',
                'notes' => 'Special expansion featuring original 151 Pokémon',
                'release_order' => 4,
            ],
            [
                'series' => 'Scarlet & Violet',
                'series_years' => '2023–2025',
                'japanese_set' => 'Ruler of the Black Flame',
                'japanese_code' => 'SV3',
                'english_set' => 'Obsidian Flames',
                'set_type' => 'Main Expansion',
                'notes' => 'Features Tera Darkness-type Charizard ex',
                'release_order' => 5,
            ],
            [
                'series' => 'Scarlet & Violet',
                'series_years' => '2023–2025',
                'japanese_set' => 'Raging Surf',
                'japanese_code' => 'SV3a',
                'english_set' => 'Paradox Rift',
                'set_type' => 'Subset',
                'notes' => 'Cards combined into English Paradox Rift',
                'release_order' => 6,
            ],
            [
                'series' => 'Scarlet & Violet',
                'series_years' => '2023–2025',
                'japanese_set' => 'Ancient Roar / Future Flash',
                'japanese_code' => 'SV4K / SV4M',
                'english_set' => 'Paradox Rift',
                'set_type' => 'Main Expansion',
                'notes' => 'Introduced Ancient and Future mechanics',
                'release_order' => 7,
            ],
            [
                'series' => 'Scarlet & Violet',
                'series_years' => '2023–2025',
                'japanese_set' => 'Shiny Treasure ex',
                'japanese_code' => 'SV4a',
                'english_set' => 'Paldean Fates',
                'set_type' => 'High-Class Pack',
                'notes' => 'Shiny Pokémon reprint pack',
                'release_order' => 8,
            ],
            [
                'series' => 'Scarlet & Violet',
                'series_years' => '2023–2025',
                'japanese_set' => 'Wild Force / Cyber Judge',
                'japanese_code' => 'SV5K / SV5M',
                'english_set' => 'Temporal Forces',
                'set_type' => 'Main Expansion',
                'notes' => 'Features Paradox Pokémon and ACE SPEC cards',
                'release_order' => 9,
            ],
            [
                'series' => 'Scarlet & Violet',
                'series_years' => '2023–2025',
                'japanese_set' => 'Crimson Haze',
                'japanese_code' => 'SV5a',
                'english_set' => 'Twilight Masquerade',
                'set_type' => 'Subset',
                'notes' => 'Cards combined into English Twilight Masquerade',
                'release_order' => 10,
            ],
            [
                'series' => 'Scarlet & Violet',
                'series_years' => '2023–2025',
                'japanese_set' => 'Mask of Change',
                'japanese_code' => 'SV6',
                'english_set' => 'Twilight Masquerade',
                'set_type' => 'Main Expansion',
                'notes' => 'Features Ogerpon and Kitakami Pokémon',
                'release_order' => 11,
            ],
            [
                'series' => 'Scarlet & Violet',
                'series_years' => '2023–2025',
                'japanese_set' => 'Night Wanderer',
                'japanese_code' => 'SV6a',
                'english_set' => 'Shrouded Fable',
                'set_type' => 'Subset',
                'notes' => 'Features Loyal Three and Pecharunt',
                'release_order' => 12,
            ],
            [
                'series' => 'Scarlet & Violet',
                'series_years' => '2023–2025',
                'japanese_set' => 'Stellar Miracle',
                'japanese_code' => 'SV7',
                'english_set' => 'Stellar Crown',
                'set_type' => 'Main Expansion',
                'notes' => 'Features Stellar Tera Pokémon and Terapagos',
                'release_order' => 13,
            ],
            [
                'series' => 'Scarlet & Violet',
                'series_years' => '2023–2025',
                'japanese_set' => 'Paradise Dragona',
                'japanese_code' => 'SV7a',
                'english_set' => 'Surging Sparks',
                'set_type' => 'Subset',
                'notes' => 'Features Dragon-type Pokémon and Alolan Exeggutor',
                'release_order' => 14,
            ],
            [
                'series' => 'Scarlet & Violet',
                'series_years' => '2023–2025',
                'japanese_set' => 'Super Electric Breaker',
                'japanese_code' => 'SV8',
                'english_set' => 'Surging Sparks',
                'set_type' => 'Main Expansion',
                'notes' => 'Features Stellar Tera Pikachu and Electric types',
                'release_order' => 15,
            ],

            // Sword & Shield Series (2019–2022)
            [
                'series' => 'Sword & Shield',
                'series_years' => '2019–2022',
                'japanese_set' => 'Sword / Shield',
                'japanese_code' => 'S1W / S1H',
                'english_set' => 'Sword & Shield Base Set',
                'set_type' => 'Main Expansion',
                'notes' => 'Introduced Pokémon V and Pokémon VMAX',
                'release_order' => 16,
            ],
            [
                'series' => 'Sword & Shield',
                'series_years' => '2019–2022',
                'japanese_set' => 'VMAX Rising',
                'japanese_code' => 'S1a',
                'english_set' => 'Rebel Clash',
                'set_type' => 'Subset',
                'notes' => 'Cards combined into Rebel Clash',
                'release_order' => 17,
            ],
            [
                'series' => 'Sword & Shield',
                'series_years' => '2019–2022',
                'japanese_set' => 'Rebellion Crash',
                'japanese_code' => 'S2',
                'english_set' => 'Rebel Clash',
                'set_type' => 'Main Expansion',
                'notes' => 'Features Toxtricity VMAX',
                'release_order' => 18,
            ],
            [
                'series' => 'Sword & Shield',
                'series_years' => '2019–2022',
                'japanese_set' => 'Explosive Walker',
                'japanese_code' => 'S2a',
                'english_set' => 'Darkness Ablaze',
                'set_type' => 'Subset',
                'notes' => 'Cards combined into Darkness Ablaze',
                'release_order' => 19,
            ],
            [
                'series' => 'Sword & Shield',
                'series_years' => '2019–2022',
                'japanese_set' => 'Infinity Zone',
                'japanese_code' => 'S3',
                'english_set' => 'Darkness Ablaze',
                'set_type' => 'Main Expansion',
                'notes' => 'Features Eternatus VMAX and Charizard VMAX',
                'release_order' => 20,
            ],
            [
                'series' => 'Sword & Shield',
                'series_years' => '2019–2022',
                'japanese_set' => 'Legendary Heartbeat',
                'japanese_code' => 'S3a',
                'english_set' => 'Vivid Voltage',
                'set_type' => 'Subset',
                'notes' => 'Introduced Amazing Rare cards',
                'release_order' => 21,
            ],
            [
                'series' => 'Sword & Shield',
                'series_years' => '2019–2022',
                'japanese_set' => 'Astonishing Volt Tackle',
                'japanese_code' => 'S4',
                'english_set' => 'Vivid Voltage',
                'set_type' => 'Main Expansion',
                'notes' => 'Features Pikachu VMAX ("Chonkachu")',
                'release_order' => 22,
            ],
            [
                'series' => 'Sword & Shield',
                'series_years' => '2019–2022',
                'japanese_set' => 'Shiny Star V',
                'japanese_code' => 'S4a',
                'english_set' => 'Shining Fates',
                'set_type' => 'High-Class Pack',
                'notes' => 'High-class shiny reprint pack',
                'release_order' => 23,
            ],
            [
                'series' => 'Sword & Shield',
                'series_years' => '2019–2022',
                'japanese_set' => 'Single Strike / Rapid Strike Master',
                'japanese_code' => 'S5I / S5R',
                'english_set' => 'Battle Styles',
                'set_type' => 'Main Expansion',
                'notes' => 'Introduced Battle Styles mechanic (Single & Rapid Strike)',
                'release_order' => 24,
            ],
            [
                'series' => 'Sword & Shield',
                'series_years' => '2019–2022',
                'japanese_set' => 'Matchless Fighter',
                'japanese_code' => 'S5a',
                'english_set' => 'Chilling Reign',
                'set_type' => 'Subset',
                'notes' => 'Features Galarian Legendary Birds',
                'release_order' => 25,
            ],
            [
                'series' => 'Sword & Shield',
                'series_years' => '2019–2022',
                'japanese_set' => 'Silver Lance / Jet-Black Spirit',
                'japanese_code' => 'S6H / S6K',
                'english_set' => 'Chilling Reign',
                'set_type' => 'Main Expansion',
                'notes' => 'Features Calyrex Rider forms',
                'release_order' => 26,
            ],
            [
                'series' => 'Sword & Shield',
                'series_years' => '2019–2022',
                'japanese_set' => 'Eevee Heroes',
                'japanese_code' => 'S6a',
                'english_set' => 'Evolving Skies',
                'set_type' => 'Subset',
                'notes' => 'Iconic Eeveelution subset with Alternate Arts (Moonbreon, etc.)',
                'release_order' => 27,
            ],
            [
                'series' => 'Sword & Shield',
                'series_years' => '2019–2022',
                'japanese_set' => 'Skyscraping Perfection / Blue Sky Stream',
                'japanese_code' => 'S7D / S7R',
                'english_set' => 'Evolving Skies',
                'set_type' => 'Main Expansion',
                'notes' => 'Features Rayquaza and Duraludon',
                'release_order' => 28,
            ],
            [
                'series' => 'Sword & Shield',
                'series_years' => '2019–2022',
                'japanese_set' => 'Fusion Arts',
                'japanese_code' => 'S8',
                'english_set' => 'Fusion Strike',
                'set_type' => 'Main Expansion',
                'notes' => 'Introduced Fusion Strike style with Mew VMAX',
                'release_order' => 29,
            ],
            [
                'series' => 'Sword & Shield',
                'series_years' => '2019–2022',
                'japanese_set' => 'VMAX Climax',
                'japanese_code' => 'S8b',
                'english_set' => 'Brilliant Stars (Trainer Gallery)',
                'set_type' => 'High-Class Pack',
                'notes' => 'Introduced Character Rare (CHR) and Character Super Rare (CSR)',
                'release_order' => 30,
            ],
            [
                'series' => 'Sword & Shield',
                'series_years' => '2019–2022',
                'japanese_set' => 'Star Birth',
                'japanese_code' => 'S9',
                'english_set' => 'Brilliant Stars',
                'set_type' => 'Main Expansion',
                'notes' => 'Introduced Pokémon VSTAR and Arceus VSTAR',
                'release_order' => 31,
            ],
            [
                'series' => 'Sword & Shield',
                'series_years' => '2019–2022',
                'japanese_set' => 'Battle Region',
                'japanese_code' => 'S9a',
                'english_set' => 'Astral Radiance',
                'set_type' => 'Subset',
                'notes' => 'Features Hisuian Pokémon and Radiant Pokémon',
                'release_order' => 32,
            ],
            [
                'series' => 'Sword & Shield',
                'series_years' => '2019–2022',
                'japanese_set' => 'Time Gazer / Space Juggler',
                'japanese_code' => 'S10D / S10P',
                'english_set' => 'Astral Radiance',
                'set_type' => 'Main Expansion',
                'notes' => 'Features Origin Forme Dialga and Palkia',
                'release_order' => 33,
            ],
            [
                'series' => 'Sword & Shield',
                'series_years' => '2019–2022',
                'japanese_set' => 'Dark Phantasma',
                'japanese_code' => 'S10a',
                'english_set' => 'Lost Origin',
                'set_type' => 'Subset',
                'notes' => 'Features Hisuian Zoroark VSTAR',
                'release_order' => 34,
            ],
            [
                'series' => 'Sword & Shield',
                'series_years' => '2019–2022',
                'japanese_set' => 'Lost Abyss',
                'japanese_code' => 'S11',
                'english_set' => 'Lost Origin',
                'set_type' => 'Main Expansion',
                'notes' => 'Reintroduced Lost Zone mechanic with Giratina VSTAR',
                'release_order' => 35,
            ],
            [
                'series' => 'Sword & Shield',
                'series_years' => '2019–2022',
                'japanese_set' => 'Incandescent Arcana',
                'japanese_code' => 'S11a',
                'english_set' => 'Silver Tempest',
                'set_type' => 'Subset',
                'notes' => 'Features Alolan Vulpix VSTAR and Serperior VSTAR',
                'release_order' => 36,
            ],
            [
                'series' => 'Sword & Shield',
                'series_years' => '2019–2022',
                'japanese_set' => 'Paradigm Trigger',
                'japanese_code' => 'S12',
                'english_set' => 'Silver Tempest',
                'set_type' => 'Main Expansion',
                'notes' => 'Features Lugia VSTAR and Regidrago/Regieleki',
                'release_order' => 37,
            ],
            [
                'series' => 'Sword & Shield',
                'series_years' => '2019–2022',
                'japanese_set' => 'VSTAR Universe',
                'japanese_code' => 'S12a',
                'english_set' => 'Crown Zenith',
                'set_type' => 'High-Class Pack',
                'notes' => 'Introduced Art Rare (AR) and Special Art Rare (SAR)',
                'release_order' => 38,
            ],

            // Sun & Moon Series (2016–2019)
            [
                'series' => 'Sun & Moon',
                'series_years' => '2016–2019',
                'japanese_set' => 'Collection Sun / Collection Moon',
                'japanese_code' => 'SM1',
                'english_set' => 'Sun & Moon Base Set',
                'set_type' => 'Main Expansion',
                'notes' => 'Introduced Pokémon-GX and Alolan regional forms',
                'release_order' => 39,
            ],
            [
                'series' => 'Sun & Moon',
                'series_years' => '2016–2019',
                'japanese_set' => 'Islands Await You / Alolan Moonlight',
                'japanese_code' => 'SM2',
                'english_set' => 'Guardians Rising',
                'set_type' => 'Main Expansion',
                'notes' => 'Features Tapu Lele-GX and Island Guardians',
                'release_order' => 40,
            ],
            [
                'series' => 'Sun & Moon',
                'series_years' => '2016–2019',
                'japanese_set' => 'To Have Seen the Battle Rainbow / Darkness that Consumes Light',
                'japanese_code' => 'SM3',
                'english_set' => 'Burning Shadows',
                'set_type' => 'Main Expansion',
                'notes' => 'Features Charizard-GX and Necrozma-GX',
                'release_order' => 41,
            ],
            [
                'series' => 'Sun & Moon',
                'series_years' => '2016–2019',
                'japanese_set' => 'Shining Legends',
                'japanese_code' => 'SM3+',
                'english_set' => 'Shining Legends',
                'set_type' => 'Subset',
                'notes' => 'Special subset featuring Shining Pokémon',
                'release_order' => 42,
            ],
            [
                'series' => 'Sun & Moon',
                'series_years' => '2016–2019',
                'japanese_set' => 'Awakened Heroes / Ultradimensional Beasts',
                'japanese_code' => 'SM4',
                'english_set' => 'Crimson Invasion',
                'set_type' => 'Main Expansion',
                'notes' => 'Introduced Ultra Beasts (Nihilego, Buzzwole)',
                'release_order' => 43,
            ],
            [
                'series' => 'Sun & Moon',
                'series_years' => '2016–2019',
                'japanese_set' => 'Ultra Sun / Ultra Moon',
                'japanese_code' => 'SM5',
                'english_set' => 'Ultra Prism',
                'set_type' => 'Main Expansion',
                'notes' => 'Introduced Prism Star cards',
                'release_order' => 44,
            ],
            [
                'series' => 'Sun & Moon',
                'series_years' => '2016–2019',
                'japanese_set' => 'Ultra Force',
                'japanese_code' => 'SM5+',
                'english_set' => 'Forbidden Light',
                'set_type' => 'Subset',
                'notes' => 'Cards combined into Forbidden Light',
                'release_order' => 45,
            ],
            [
                'series' => 'Sun & Moon',
                'series_years' => '2016–2019',
                'japanese_set' => 'Forbidden Light',
                'japanese_code' => 'SM6',
                'english_set' => 'Forbidden Light',
                'set_type' => 'Main Expansion',
                'notes' => 'Features Ultra Necrozma-GX',
                'release_order' => 46,
            ],
            [
                'series' => 'Sun & Moon',
                'series_years' => '2016–2019',
                'japanese_set' => 'Champion Road',
                'japanese_code' => 'SM6a',
                'english_set' => 'Celestial Storm',
                'set_type' => 'Subset',
                'notes' => 'Nostalgic callbacks to EX-era mechanics',
                'release_order' => 47,
            ],
            [
                'series' => 'Sun & Moon',
                'series_years' => '2016–2019',
                'japanese_set' => 'Sky-Splitting Charisma',
                'japanese_code' => 'SM7',
                'english_set' => 'Celestial Storm',
                'set_type' => 'Main Expansion',
                'notes' => 'Features Rayquaza-GX and Hoenn Pokémon',
                'release_order' => 48,
            ],
            [
                'series' => 'Sun & Moon',
                'series_years' => '2016–2019',
                'japanese_set' => 'Thunderclap Spark',
                'japanese_code' => 'SM7a',
                'english_set' => 'Lost Thunder',
                'set_type' => 'Subset',
                'notes' => 'Features Zeraora-GX',
                'release_order' => 49,
            ],
            [
                'series' => 'Sun & Moon',
                'series_years' => '2016–2019',
                'japanese_set' => 'Fairy Rise',
                'japanese_code' => 'SM7b',
                'english_set' => 'Lost Thunder',
                'set_type' => 'Subset',
                'notes' => 'Features Alolan Ninetales-GX and Mimikyu-GX',
                'release_order' => 50,
            ],
            [
                'series' => 'Sun & Moon',
                'series_years' => '2016–2019',
                'japanese_set' => 'Super-Burst Impact',
                'japanese_code' => 'SM8',
                'english_set' => 'Lost Thunder',
                'set_type' => 'Main Expansion',
                'notes' => 'Features Lugia-GX and Blacephalon-GX',
                'release_order' => 51,
            ],
            [
                'series' => 'Sun & Moon',
                'series_years' => '2016–2019',
                'japanese_set' => 'Dark Order',
                'japanese_code' => 'SM8a',
                'english_set' => 'Team Up',
                'set_type' => 'Subset',
                'notes' => 'Features Dark and Metal type focus',
                'release_order' => 52,
            ],
            [
                'series' => 'Sun & Moon',
                'series_years' => '2016–2019',
                'japanese_set' => 'GX Ultra Shiny',
                'japanese_code' => 'SM8b',
                'english_set' => 'Hidden Fates',
                'set_type' => 'High-Class Pack',
                'notes' => 'Precursor to Hidden Fates Shiny Vault',
                'release_order' => 53,
            ],
            [
                'series' => 'Sun & Moon',
                'series_years' => '2016–2019',
                'japanese_set' => 'Tag Bolt',
                'japanese_code' => 'SM9',
                'english_set' => 'Team Up',
                'set_type' => 'Main Expansion',
                'notes' => 'Introduced TAG TEAM Pokémon-GX (Pikachu & Zekrom-GX)',
                'release_order' => 54,
            ],
            [
                'series' => 'Sun & Moon',
                'series_years' => '2016–2019',
                'japanese_set' => 'Night Unison',
                'japanese_code' => 'SM9a',
                'english_set' => 'Unbroken Bonds',
                'set_type' => 'Subset',
                'notes' => 'Features Greninja & Zoroark-GX',
                'release_order' => 55,
            ],
            [
                'series' => 'Sun & Moon',
                'series_years' => '2016–2019',
                'japanese_set' => 'Full Metal Wall',
                'japanese_code' => 'SM9b',
                'english_set' => 'Unbroken Bonds',
                'set_type' => 'Subset',
                'notes' => 'Features Lucario & Melmetal-GX',
                'release_order' => 56,
            ],
            [
                'series' => 'Sun & Moon',
                'series_years' => '2016–2019',
                'japanese_set' => 'Double Blaze',
                'japanese_code' => 'SM10',
                'english_set' => 'Unbroken Bonds',
                'set_type' => 'Main Expansion',
                'notes' => 'Features Reshiram & Charizard-GX',
                'release_order' => 57,
            ],
            [
                'series' => 'Sun & Moon',
                'series_years' => '2016–2019',
                'japanese_set' => 'GG End',
                'japanese_code' => 'SM10a',
                'english_set' => 'Unified Minds',
                'set_type' => 'Subset',
                'notes' => 'Features Garchomp & Giratina-GX',
                'release_order' => 58,
            ],
            [
                'series' => 'Sun & Moon',
                'series_years' => '2016–2019',
                'japanese_set' => 'Sky Legend',
                'japanese_code' => 'SM10b',
                'english_set' => 'Unified Minds',
                'set_type' => 'Subset',
                'notes' => 'Features Legendary Birds Trio TAG TEAM GX',
                'release_order' => 59,
            ],
            [
                'series' => 'Sun & Moon',
                'series_years' => '2016–2019',
                'japanese_set' => 'Miracle Twin',
                'japanese_code' => 'SM11',
                'english_set' => 'Unified Minds',
                'set_type' => 'Main Expansion',
                'notes' => 'Features Mewtwo & Mew-GX',
                'release_order' => 60,
            ],
            [
                'series' => 'Sun & Moon',
                'series_years' => '2016–2019',
                'japanese_set' => 'Remix Bout',
                'japanese_code' => 'SM11a',
                'english_set' => 'Cosmic Eclipse',
                'set_type' => 'Subset',
                'notes' => 'Features Kanto Starter TAG TEAMs and Character Rares',
                'release_order' => 61,
            ],
            [
                'series' => 'Sun & Moon',
                'series_years' => '2016–2019',
                'japanese_set' => 'Dream League',
                'japanese_code' => 'SM11b',
                'english_set' => 'Cosmic Eclipse',
                'set_type' => 'Subset',
                'notes' => 'Origin of Character Rare trainer artwork',
                'release_order' => 62,
            ],
            [
                'series' => 'Sun & Moon',
                'series_years' => '2016–2019',
                'japanese_set' => 'Alter Genesis',
                'japanese_code' => 'SM12',
                'english_set' => 'Cosmic Eclipse',
                'set_type' => 'Main Expansion',
                'notes' => 'Features Arceus & Dialga & Palkia-GX (ADP)',
                'release_order' => 63,
            ],
            [
                'series' => 'Sun & Moon',
                'series_years' => '2016–2019',
                'japanese_set' => 'Tag All Stars',
                'japanese_code' => 'SM12a',
                'english_set' => 'Distributed as English Promos',
                'set_type' => 'High-Class Pack',
                'notes' => 'High-class pack, many cards distributed as English Promos and Small But Mighty Collection',
                'release_order' => 64,
            ],

            // XY Series (2013–2016)
            [
                'series' => 'XY',
                'series_years' => '2013–2016',
                'japanese_set' => 'Collection X / Collection Y',
                'japanese_code' => 'XY1',
                'english_set' => 'XY Base Set',
                'set_type' => 'Main Expansion',
                'notes' => 'Introduced Fairy type and Mega Evolution Pokémon-EX',
                'release_order' => 65,
            ],
            [
                'series' => 'XY',
                'series_years' => '2013–2016',
                'japanese_set' => 'Wild Blaze',
                'japanese_code' => 'XY2',
                'english_set' => 'Flashfire',
                'set_type' => 'Main Expansion',
                'notes' => 'Features Mega Charizard-EX (X and Y versions)',
                'release_order' => 66,
            ],
            [
                'series' => 'XY',
                'series_years' => '2013–2016',
                'japanese_set' => 'Rising Fist',
                'japanese_code' => 'XY3',
                'english_set' => 'Furious Fists',
                'set_type' => 'Main Expansion',
                'notes' => 'Features Mega Lucario-EX',
                'release_order' => 67,
            ],
            [
                'series' => 'XY',
                'series_years' => '2013–2016',
                'japanese_set' => 'Phantom Gate',
                'japanese_code' => 'XY4',
                'english_set' => 'Phantom Forces',
                'set_type' => 'Main Expansion',
                'notes' => 'Features Mega Gengar-EX',
                'release_order' => 68,
            ],
            [
                'series' => 'XY',
                'series_years' => '2013–2016',
                'japanese_set' => 'Gaia Volcano / Tidal Storm',
                'japanese_code' => 'XY5',
                'english_set' => 'Primal Clash',
                'set_type' => 'Main Expansion',
                'notes' => 'Introduced Primal Reversion Groudon & Kyogre',
                'release_order' => 69,
            ],
            [
                'series' => 'XY',
                'series_years' => '2013–2016',
                'japanese_set' => 'Emerald Break',
                'japanese_code' => 'XY6',
                'english_set' => 'Roaring Skies',
                'set_type' => 'Main Expansion',
                'notes' => 'Features Mega Rayquaza-EX and Shaymin-EX',
                'release_order' => 70,
            ],
            [
                'series' => 'XY',
                'series_years' => '2013–2016',
                'japanese_set' => 'Bandit Ring',
                'japanese_code' => 'XY7',
                'english_set' => 'Ancient Origins',
                'set_type' => 'Main Expansion',
                'notes' => 'Features Hoopa-EX and Shiny Mega Rayquaza',
                'release_order' => 71,
            ],
            [
                'series' => 'XY',
                'series_years' => '2013–2016',
                'japanese_set' => 'Blue Shock / Red Flash',
                'japanese_code' => 'XY8',
                'english_set' => 'BREAKthrough',
                'set_type' => 'Main Expansion',
                'notes' => 'Introduced BREAK Evolution and Mega Mewtwo-EX',
                'release_order' => 72,
            ],
            [
                'series' => 'XY',
                'series_years' => '2013–2016',
                'japanese_set' => 'Rage of the Broken Heavens',
                'japanese_code' => 'XY9',
                'english_set' => 'BREAKpoint',
                'set_type' => 'Main Expansion',
                'notes' => 'Features Mega Gyarados-EX',
                'release_order' => 73,
            ],
            [
                'series' => 'XY',
                'series_years' => '2013–2016',
                'japanese_set' => 'Generations / Starter Pack',
                'japanese_code' => 'XY',
                'english_set' => 'Generations',
                'set_type' => 'Special Expansion',
                'notes' => '20th anniversary special release including Radiant Collection',
                'release_order' => 74,
            ],
            [
                'series' => 'XY',
                'series_years' => '2013–2016',
                'japanese_set' => 'Awakening Psychic King',
                'japanese_code' => 'XY10',
                'english_set' => 'Fates Collide',
                'set_type' => 'Main Expansion',
                'notes' => 'Features Mega Alakazam-EX and Zygarde',
                'release_order' => 75,
            ],
            [
                'series' => 'XY',
                'series_years' => '2013–2016',
                'japanese_set' => 'Explosive Fighter / Cruel Traitor',
                'japanese_code' => 'XY11',
                'english_set' => 'Steam Siege',
                'set_type' => 'Main Expansion',
                'notes' => 'Introduced Dual-Type Pokémon and Mega Gardevoir-EX',
                'release_order' => 76,
            ],
            [
                'series' => 'XY',
                'series_years' => '2013–2016',
                'japanese_set' => '20th Anniversary Concept Pack',
                'japanese_code' => 'CP6',
                'english_set' => 'Evolutions',
                'set_type' => 'Special Expansion',
                'notes' => 'Base Set retro anniversary reprint expansion',
                'release_order' => 77,
            ],

            // Black & White Series (2010–2013)
            [
                'series' => 'Black & White',
                'series_years' => '2010–2013',
                'japanese_set' => 'Black Collection / White Collection',
                'japanese_code' => 'BW1',
                'english_set' => 'Black & White Base Set',
                'set_type' => 'Main Expansion',
                'notes' => 'Introduced full-art Secret Rare Reshiram and Zekrom',
                'release_order' => 78,
            ],
            [
                'series' => 'Black & White',
                'series_years' => '2010–2013',
                'japanese_set' => 'Red Collection',
                'japanese_code' => 'BW2',
                'english_set' => 'Emerging Powers',
                'set_type' => 'Main Expansion',
                'notes' => 'Features Victini and Cobalion',
                'release_order' => 79,
            ],
            [
                'series' => 'Black & White',
                'series_years' => '2010–2013',
                'japanese_set' => 'Psycho Drive / Hail Blizzard',
                'japanese_code' => 'BW3',
                'english_set' => 'Next Destinies',
                'set_type' => 'Main Expansion',
                'notes' => 'Introduced Pokémon-EX (Mewtwo-EX, Shaymin-EX)',
                'release_order' => 80,
            ],
            [
                'series' => 'Black & White',
                'series_years' => '2010–2013',
                'japanese_set' => 'Dark Rush',
                'japanese_code' => 'BW4',
                'english_set' => 'Dark Explorers',
                'set_type' => 'Main Expansion',
                'notes' => 'Features Darkrai-EX',
                'release_order' => 81,
            ],
            [
                'series' => 'Black & White',
                'series_years' => '2010–2013',
                'japanese_set' => 'Dragon Blade / Dragon Blast',
                'japanese_code' => 'BW5',
                'english_set' => 'Dragons Exalted',
                'set_type' => 'Main Expansion',
                'notes' => 'Introduced the Dragon type and Rayquaza-EX',
                'release_order' => 82,
            ],
            [
                'series' => 'Black & White',
                'series_years' => '2010–2013',
                'japanese_set' => 'Freeze Bolt / Cold Flare',
                'japanese_code' => 'BW6',
                'english_set' => 'Boundaries Crossed',
                'set_type' => 'Main Expansion',
                'notes' => 'Introduced ACE SPEC cards and Black/White Kyurem-EX',
                'release_order' => 83,
            ],
            [
                'series' => 'Black & White',
                'series_years' => '2010–2013',
                'japanese_set' => 'Spiral Force / Thunder Knuckle',
                'japanese_code' => 'BW7',
                'english_set' => 'Plasma Freeze',
                'set_type' => 'Main Expansion',
                'notes' => 'Introduced Team Plasma cards',
                'release_order' => 84,
            ],
            [
                'series' => 'Black & White',
                'series_years' => '2010–2013',
                'japanese_set' => 'Megalo Cannon',
                'japanese_code' => 'BW8',
                'english_set' => 'Plasma Blast',
                'set_type' => 'Main Expansion',
                'notes' => 'Features Genesect-EX and Virizion-EX',
                'release_order' => 85,
            ],
            [
                'series' => 'Black & White',
                'series_years' => '2010–2013',
                'japanese_set' => 'EX Battle Boost',
                'japanese_code' => 'EBB',
                'english_set' => 'Legendary Treasures',
                'set_type' => 'High-Class Pack',
                'notes' => 'High-class reprint pack with Radiant Collection equivalent',
                'release_order' => 86,
            ],

            // Classic, Neo, e-Card, EX, DP, Platinum, & HGSS Series (1996–2010)
            [
                'series' => 'Original / Classic Series',
                'series_years' => '1996–2000',
                'japanese_set' => 'Expansion Pack / Jungle / Mystery of the Fossils / Rocket Gang / Leaders\' Stadium / Challenge from the Darkness',
                'japanese_code' => 'Classic Block',
                'english_set' => 'Base Set, Jungle, Fossil, Base Set 2, Team Rocket, Gym Heroes, Gym Challenge',
                'set_type' => 'Era Block',
                'notes' => 'Japanese vintage sets heavily parallel English sets, though promotional gaps exist.',
                'release_order' => 87,
            ],
            [
                'series' => 'Neo Series',
                'series_years' => '2000–2002',
                'japanese_set' => 'Gold, Silver, to a New World... / Crossing the Ruins... / Awakening Legends / Darkness, and to Light...',
                'japanese_code' => 'Neo Block',
                'english_set' => 'Neo Genesis, Neo Discovery, Neo Revelation, Neo Destiny, Legendary Collection',
                'set_type' => 'Era Block',
                'notes' => 'Introduced Generation 2 Pokémon, Darkness & Metal types, and Shining Pokémon.',
                'release_order' => 88,
            ],
            [
                'series' => 'e-Card Series',
                'series_years' => '2001–2003',
                'japanese_set' => 'Base Expansion Pack / The Town on No Map / Wind from the Sea / Split Earth / Mysterious Mountains',
                'japanese_code' => 'e-Card Block',
                'english_set' => 'Expedition Base Set, Aquapolis, Skyridge',
                'set_type' => 'Era Block',
                'notes' => 'Dot-code strips compatible with Nintendo e-Reader accessory.',
                'release_order' => 89,
            ],
            [
                'series' => 'EX Series',
                'series_years' => '2003–2007',
                'japanese_set' => 'ADV & PCG Blocks (R&S, Magma vs Aqua, Miracle of the Desert, Flight of Legends, Clash of the Blue Sky, Rocket Gang Strikes Back, Golden Sky, Silvery Ocean, Mirage Forest, Holon Research Tower, Holon Phantom, Miracle Crystal, Offense and Defense of the Furthest Ends, World Champions Pack)',
                'japanese_code' => 'ADV / PCG Block',
                'english_set' => 'Ruby & Sapphire, Sandstorm, Dragon, Team Magma vs Team Aqua, Hidden Legends, FireRed & LeafGreen, Team Rocket Returns, Deoxys, Emerald, Unseen Forces, Delta Species, Legend Maker, Holon Phantoms, Crystal Guardians, Dragon Frontiers, Power Keepers',
                'set_type' => 'Era Block',
                'notes' => 'Introduced Pokémon-ex, Pokémon Star (Gold Star), and Delta Species.',
                'release_order' => 90,
            ],
            [
                'series' => 'Diamond & Pearl Series',
                'series_years' => '2006–2008',
                'japanese_set' => 'Space-Time Creation / Secret of the Lakes / Shining Darkness / Moonlit Pursuit / Cry from the Mysterious / Temple of Anger / Cry from the Mysterious',
                'japanese_code' => 'DP Block',
                'english_set' => 'Diamond & Pearl Base Set, Mysterious Treasures, Secret Wonders, Great Encounters, Majestic Dawn, Legends Awakened, Stormfront',
                'set_type' => 'Era Block',
                'notes' => 'Introduced Pokémon LV.X and Sinnoh region Pokémon.',
                'release_order' => 91,
            ],
            [
                'series' => 'Platinum Series',
                'series_years' => '2008–2009',
                'japanese_set' => 'Galactic\'s Conquest / Bonds to the End of Time / Beat of the Frontier / Advent of Arceus',
                'japanese_code' => 'Pt Block',
                'english_set' => 'Platinum Base Set, Rising Rivals, Supreme Victors, Arceus',
                'set_type' => 'Era Block',
                'notes' => 'Introduced Pokémon SP (Gym Leader / Champion owned) and Arceus mechanic.',
                'release_order' => 92,
            ],
            [
                'series' => 'HeartGold & SoulSilver Series',
                'series_years' => '2009–2011',
                'japanese_set' => 'HeartGold & SoulSilver Collection / Reviving Legends / Clash at the Summit / Lost Link',
                'japanese_code' => 'HGSS / L Block',
                'english_set' => 'HeartGold & SoulSilver Base Set, Unleashed, Undaunted, Triumphant, Call of Legends',
                'set_type' => 'Era Block',
                'notes' => 'Introduced Pokémon Prime and Pokémon LEGEND two-card combination pieces.',
                'release_order' => 93,
            ],
        ];

        foreach ($sets as $set) {
            RefPokemonSet::updateOrCreate(
                [
                    'series' => $set['series'],
                    'japanese_set' => $set['japanese_set'],
                ],
                $set
            );
        }
    }
}
